### ISSUE TITLE
website down?

### ISSUE THREAD

**Issue by psteinb** [mpicbg-scicomp/gearshifft_results#12]
I get this error message when trying to access the rshiny app
![image](https://user-images.githubusercontent.com/1465603/49007098-eaa04700-f16a-11e8-97f2-450fa4f242c4.png)
Any idea why this is?

**Comment by psteinb** [comment]
same on firefox
![image](https://user-images.githubusercontent.com/1465603/49007180-2509e400-f16b-11e8-8890-830ed993c7ab.png)

**Comment by tdd11235813** [comment]
thanks for spotting, please try again, it should work now.
